[profile.release]
debug = true

[workspace]
resolver = "2"
members = [
    "aoc2023lib",
    "day01-trebuchet",
    "day02-cube-conundrum",
    "day03-gear",
    "day04-scratchcards",
    "day05-seed",
    "day06-wait",
]
